name: Android Fastlane Workflow

on:
  push:
    branches:
      - "**"

jobs:
  distribute_to_firebase:
    runs-on: windows-latest

    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.4"
          bundler-cache: true
          working-directory: android

      - name: Build and distribute app
        env:
          FIREBASE_CLI_TOKEN: 1//09h1g-G_vGzFCCgYIARAAGAkSNwF-L9Irp9XmAm2JAR0P-vmO6q61rA_Mb57QfgtCH3NtLi2Qm6v5UJk7s-gvDxm7hS38iLWu0-E
        run: |
          bundle exec fastlane android firebasedistribution
        working-directory: android
